### PR TITLE
Created CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by DiNitride**
Created a contributors file that others can add themselves onto as discussed in #26

### CODE REVIEW

**Comment by amit2rockon** [comment]
@DiNitride  it would be better if you write a python script that fetch the list of contributors of this repo from GitHub  using existing python libraries like selenium . etc. So that it does not need to be hard coded every single time.

**Comment by DiNitride** [comment]
@amit2rockon I have written a script however to access repo collaborators you must have push access to the repository. I can complete the script however only those users (i.e. you) will be able to run the script to update the file.

**Comment by amit2rockon** [comment]
https://api.github.com/repos/amit2rockon/pymit/contributors?page=1&?

So then you can parse the user-id :)

**Comment by DiNitride** [comment]
Weird, I made a request to this URL and it required authentication
https://developer.github.com/v3/repos/collaborators/#list-collaborators

I'll use the link you posted

**Comment by amit2rockon** [comment]
@DiNitride  resolve the conflicts or rebase the repo.  also you don't require "auth" for parsing this link , So you may avoid it by removing "auth" from this line `r = requests.get(CONTRIBURORS_URL,auth)  ` .

**Comment by amit2rockon** [comment]
Thanks @DiNitride,  You did it! it looks good to be merged now .

**Comment by DiNitride** [comment]
@amit2rockon I was in the process of finishing everything when you posted that

**Pull request merged**
